services:
  satplatformserver:
    image: satplatformserver
    build:
      context: server
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    restart: always
    ports:
      - 5000:5000
